apiVersion: apps/v1
kind: Deployment
metadata:
  name: chestgan-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chestgan-pipeline
  template:
    metadata:
      labels:
        app: chestgan-pipeline
    spec:
      containers:
        - name: chestgan-pipeline
          image: pperezdem/metaflow-pipeline:latest
          env:
            - name: USER
              value: "ChestGAN"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "4Gi"
              cpu: "4"